'use client';
/**
 * WhatsApp screens — inbox (triage, thread, composer with the 24h window and the
 * template picker), templates admin, review queue, and the accounts panel.
 * Behaviour mirrors apps/web/app/admin/whatsapp in production; the template
 * picker is the piece production still stubs ("coming in the next chunk").
 */
import React, { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Clock, Lock, Send, LayoutTemplate, Plus, Trash2, Pause, Play, MessageSquare, Phone, UserPlus, ArrowLeftRight, Archive, RotateCcw, ShieldAlert, Search, RefreshCw, ExternalLink, Info } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Table, TableHeader, TableHead, TableRow, TableCell, TableBody } from '@/components/ui/table';
import { Button, Panel, Pick, Empty, Avatar, Pill, StageMini, DateText, Head, SLA } from './ui';
import { useMasar } from './context';
import { labels, type Journey } from '@/lib/masar/model';
import { person, product, canEdit, canManage } from '@/lib/masar/engine';
import { windowState, windowRemainingMs, formatRemaining, renderTemplateBody, countTemplateVariables, conversationFor, isCaptain, TEMPLATE_CATEGORIES, TEMPLATE_STATUSES, type Conversation, type WhatsAppTemplate, type WhatsAppReview, type ReviewResolution } from '@/lib/masar/whatsapp';

const SOURCE_LABEL: Record<string, string> = { inbound_route: 'توجيه وارد', manual_handover: 'تسليم يدوي', outbound_self: 'استلام بالرد', migrated: 'مرحّل', lead_propagation: 'من الرحلة' };
const STATUS_LABEL: Record<string, string> = { queued: 'في الطابور', sent: 'أُرسلت', delivered: 'وصلت', read: 'قُرئت', failed: 'فشلت', received: 'واردة' };
const REASON_LABEL: Record<string, [string, string, string]> = { captain_active: ['كابتن نشط', 'الرقم يخص كابتن نشط بالفعل؛ لا يُنشأ ليد جديد تلقائيًا.', 'gold'], duplicate_lead: ['رحلات متعددة', 'أكثر من رحلة مفتوحة لنفس الرقم؛ اختر الرحلة الصحيحة.', 'blue'], unmatched_after_routing: ['بلا مرشحة', 'لم تُوجد موظفة مؤهلة عند التوجيه؛ الليد ينتظر قرارًا بشريًا.', 'red'] };

/* ---------- window pip (mirrors components/whatsapp/window-pip.tsx) ---------- */
export function WindowPip({ conv, compact = false }: { conv?: Conversation; compact?: boolean }) {
  const { s } = useMasar();
  const st = windowState(conv, s.now), left = formatRemaining(windowRemainingMs(conv, s.now));
  const color = st === 'open' ? 'green' : st === 'closing_soon' ? 'gold' : 'red';
  const Icon = st === 'open' ? CheckCircle2 : st === 'closing_soon' ? Clock : Lock;
  const text = st === 'open' ? `النافذة مفتوحة · باقي ${left}` : st === 'closing_soon' ? `تُغلق خلال ${left}` : 'النافذة مغلقة — قوالب فقط';
  if (compact) return <span className={`pill ${color}`} title={text} style={{ padding: '3px 6px' }}><Icon size={12} /></span>;
  return <Pill color={color}><Icon size={13} />{text}</Pill>;
}

function useNowTick() { const [, set] = useState(0); useEffect(() => { const id = setInterval(() => set(x => x + 1), 60_000); return () => clearInterval(id); }, []); }

/* ---------- inbox ---------- */
export function InboxPage() {
  const { s, a, t, go, open, action, busy } = useMasar();
  useNowTick();
  const qs = typeof location === 'undefined' ? null : new URLSearchParams(location.hash.split('?')[1]).get('journey');
  const [selected, setSelected] = useState(''), [text, setText] = useState(''), [search, setSearch] = useState(''), [account, setAccount] = useState('all'), [status, setStatus] = useState('open'), [mine, setMine] = useState(a.role === 'agent'), [queue, setQueue] = useState('all'), [picker, setPicker] = useState(false), [dialog, setDialog] = useState<'assign' | 'handover' | null>(null);
  const journeyOf = (c: Conversation) => c.journeyId ? s.journeys.find(j => j.id === c.journeyId) : undefined;
  const nameOf = (c: Conversation) => (c.personId && s.people.find(p => p.id === c.personId)?.name) || c.phone;
  const review = (c: Conversation) => s.waReviews.find(r => r.conversationId === c.id && !r.resolvedAt);
  const dayStart = s.now - (s.now % 86_400_000);
  const base = s.conversations.filter(c => account === 'all' || c.accountId === account);
  const summary = { open: base.filter(c => c.status === 'open').length, unassigned: base.filter(c => c.status === 'open' && !c.assignedToId).length, mine: base.filter(c => c.assignedToId === a.id).length, waitingReply: base.filter(c => c.status === 'open' && c.lastInboundAt && c.lastInboundAt >= c.lastMessageAt).length, needsReview: base.filter(c => review(c)).length, linked: base.filter(c => c.journeyId).length, unlinked: base.filter(c => c.status === 'open' && !c.journeyId).length, today: base.filter(c => c.lastMessageAt >= dayStart).length };
  const list = base.filter(c => (status === 'all' || c.status === status) && (!mine || c.assignedToId === a.id) && (queue === 'all' || (queue === 'unassigned' && !c.assignedToId) || (queue === 'waiting' && c.lastInboundAt && c.lastInboundAt >= c.lastMessageAt) || (queue === 'review' && review(c)) || (queue === 'unlinked' && !c.journeyId)) && (!search || nameOf(c).includes(search) || c.phone.includes(search))).sort((x, y) => y.lastMessageAt - x.lastMessageAt);
  const fromQs = qs ? s.conversations.find(c => c.journeyId === qs) : undefined;
  const c = list.find(c => c.id === selected) || fromQs || list[0];
  const j = c ? journeyOf(c) : undefined;
  const acc = c ? s.waAccounts.find(x => x.id === c.accountId) : undefined;
  const st = windowState(c, s.now);
  const closed = c?.status === 'closed';
  const editable = !!(j && canEdit(a, j) && j.state === 'open' && j.ownerId);
  const freeformDisabled = !editable || closed || st === 'closed' || !acc?.isActive;
  const msgs = c ? s.messages.filter(m => m.conversationId === c.id).sort((x, y) => x.at - y.at) : [];
  const priorHidden = c?.handoverMode && c.handoverMode !== 'full' && a.role === 'agent';
  const send = async () => { if (!j || !text.trim()) return; try { await action({ type: 'send_message', id: j.id, text }); setText(''); } catch { } };
  const kpi = (k: keyof typeof summary, label: string, q = 'all') => <button key={k} className={`panel stat ${queue === q ? 'selected' : ''}`} style={{ padding: '12px 14px', gap: 10, '--stage': 'var(--brand-500)', borderColor: queue === q ? 'var(--brand-500)' : undefined } as React.CSSProperties} onClick={() => setQueue(q)}><div><strong style={{ fontSize: 22 }}>{summary[k]}</strong><p>{label}</p></div></button>;
  return <>
    <Head title={t('صندوق الوارد', 'Inbox')} subtitle={t('رقم لكل شركة · المحادثة تتبع مالكة الرحلة · نافذة 24 ساعة للرسائل الحرة', 'One number per company · conversations follow the owner · 24h window')} actions={<><Button variant="outline" onClick={() => open('inbound')}><Plus size={16} />{t('محاكاة رسالة واردة', 'Simulate inbound')}</Button>{a.role !== 'agent' && <Button variant="outline" onClick={() => go('wa-templates')}><LayoutTemplate size={16} />{t('القوالب', 'Templates')}</Button>}</>} />
    <div className="stats-grid" style={{ gridTemplateColumns: 'repeat(6, minmax(0,1fr))', marginBottom: 16 }}>{kpi('open', 'مفتوحة', 'all')}{kpi('unassigned', 'غير مسندة', 'unassigned')}{kpi('waitingReply', 'في انتظار الرد', 'waiting')}{kpi('needsReview', 'تحتاج مراجعة', 'review')}{kpi('unlinked', 'غير مرتبطة برحلة', 'unlinked')}{kpi('today', 'اليوم', 'all')}</div>
    <Panel body={false}>
      <div className="filters"><div className="global-search" style={{ width: 260 }}><Search /><Input placeholder={t('بحث بالاسم أو الرقم', 'Search name or phone')} value={search} onChange={e => setSearch(e.target.value)} /></div>{s.waAccounts.length > 1 && <Pick value={account} onChange={setAccount} options={[{ value: 'all', label: 'كل الحسابات' }, ...s.waAccounts.map(x => ({ value: x.id, label: `${x.displayName} (${x.phoneNumber})` }))]} />}<Pick value={status} onChange={setStatus} options={[{ value: 'open', label: 'مفتوحة' }, { value: 'closed', label: 'مغلقة' }, { value: 'all', label: 'الكل' }]} /><div className="segmented"><button className={mine ? 'active' : ''} onClick={() => setMine(true)}>{t('محادثاتي', 'Mine')}</button><button className={!mine ? 'active' : ''} onClick={() => setMine(false)}>{t('الكل', 'All')}</button></div><span className="small muted" style={{ marginInlineStart: 'auto' }}>{list.length} {t('محادثة', 'conversations')}</span></div>
      <div className="chat-shell" style={{ gridTemplateColumns: '320px minmax(0,1fr) 300px' }}>
        <aside className="chat-list">{list.map(x => { const jx = journeyOf(x), rv = review(x), unread = x.lastInboundAt && x.lastInboundAt >= x.lastMessageAt; return <button key={x.id} className={`chat-item ${c?.id === x.id ? 'selected' : ''}`} onClick={() => setSelected(x.id)}><div className="person-cell"><Avatar name={nameOf(x)} /><div style={{ minWidth: 0, flex: 1 }}><div className="row-between"><strong>{nameOf(x)}</strong><DateText at={x.lastMessageAt} time /></div><small style={{ fontFamily: 'inherit', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', maxWidth: 220 }}>{x.lastMessageText || x.phone}</small><div className="actions" style={{ gap: 4, marginTop: 6, flexWrap: 'wrap' }}>{x.status === 'closed' && <Pill>مغلقة</Pill>}<WindowPip conv={x} compact />{x.assignmentSource && <Pill>{SOURCE_LABEL[x.assignmentSource]}</Pill>}{!mine && x.assignedToId && <Pill>{s.agents.find(u => u.id === x.assignedToId)?.name}</Pill>}{x.personId && isCaptain(s, x.personId) && <Pill color="purple">Captain</Pill>}{rv && <Pill color="red"><ShieldAlert size={12} />مراجعة</Pill>}{jx && <Pill color="blue">{labels[jx.stage]}</Pill>}{unread && <span style={{ width: 8, height: 8, borderRadius: 4, background: 'var(--brand-500)' }} />}</div></div></div></button>; })}{!list.length && <Empty text={t('لا توجد محادثات في هذا العرض', 'No conversations in this view')} />}</aside>
        {c ? <div className="chat-room">
          <div className="panel-head" style={{ flexWrap: 'wrap', gap: 8 }}><div className="person-cell"><Avatar name={nameOf(c)} /><div><div className="actions" style={{ gap: 6 }}><strong>{nameOf(c)}</strong>{c.personId && isCaptain(s, c.personId) && <Pill color="purple">Captain</Pill>}{c.status === 'closed' && <Pill>مغلقة</Pill>}{c.assignmentSource && <Pill>{SOURCE_LABEL[c.assignmentSource]}</Pill>}</div><p className="small muted"><Phone size={12} style={{ display: 'inline', marginInlineEnd: 4 }} /><span className="mono">{c.phone}</span> · {acc?.displayName} <span className="mono">{acc?.phoneNumber}</span> · {c.assignedToId ? s.agents.find(u => u.id === c.assignedToId)?.name : t('غير مسندة', 'Unassigned')}</p></div></div><div className="actions"><WindowPip conv={c} />{a.role !== 'agent' && <>{!closed && <Button size="sm" variant="outline" onClick={() => setDialog('assign')}><UserPlus size={14} />{t('إسناد', 'Assign')}</Button>}{j && !closed && <Button size="sm" variant="outline" onClick={() => setDialog('handover')}><ArrowLeftRight size={14} />{t('تسليم', 'Handover')}</Button>}</>}{!closed ? <Button size="sm" variant="ghost" onClick={() => action({ type: 'wa_conversation', id: c.id, op: 'close' }).catch(() => { })}><Archive size={14} />{t('إغلاق', 'Close')}</Button> : <Button size="sm" variant="ghost" onClick={() => action({ type: 'wa_conversation', id: c.id, op: 'reopen' }).catch(() => { })}><RotateCcw size={14} />{t('إعادة فتح', 'Reopen')}</Button>}</div></div>
          {priorHidden && <div className="insight" style={{ borderRadius: 0 }}><Info size={16} />{t(`تسليم ${c.handoverMode === 'clean' ? 'نظيف' : 'بملخص'}: الرسائل السابقة للتسليم مخفية عنك بقاعدة «الأشد يفوز».`, 'Prior messages hidden by the handover mode.')}</div>}
          <div className="chat-messages">{msgs.map(m => <div key={m.id} className={`bubble ${m.direction === 'out' ? 'out' : ''}`}>{m.messageType === 'template' && <span className="pill blue" style={{ marginBottom: 6, display: 'inline-flex' }}><LayoutTemplate size={11} />{m.templateName} · {m.templateLanguage}</span>}{m.text}<small><DateText at={m.at} time /> {m.direction === 'out' && <>· {STATUS_LABEL[m.state]} {m.state === 'read' ? '✓✓' : m.state === 'delivered' ? '✓✓' : m.state === 'sent' ? '✓' : ''}</>}{m.direction === 'out' && a.role !== 'agent' && m.state !== 'read' && m.state !== 'failed' && <> · <button className="link-button" style={{ fontSize: 11 }} onClick={() => action({ type: 'wa_message_status', id: m.id, status: m.state === 'sent' ? 'delivered' : 'read' }).catch(() => { })}>محاكاة {m.state === 'sent' ? 'التسليم' : 'القراءة'}</button></>}</small></div>)}{!msgs.length && <Empty text={t('لا رسائل ظاهرة', 'No visible messages')} />}</div>
          {closed ? <div className="insight" style={{ borderRadius: 0 }}><Info size={16} />{t('هذه المحادثة مغلقة. أعد فتحها قبل الإرسال.', 'This conversation is closed. Reopen it before sending.')}</div> : !acc?.isActive ? <div className="notifier" style={{ margin: 0, borderRadius: 0 }}>{t('حساب واتساب موقوف؛ لا يمكن الإرسال من هذا الرقم.', 'Account disabled.')}</div> : st === 'closed' ? <div className="notifier" style={{ margin: 0, borderRadius: 0, background: 'var(--critical-bg)', color: 'var(--critical-fg)', borderColor: 'var(--critical)' }}><Lock size={14} style={{ display: 'inline', marginInlineEnd: 6 }} />{t('نافذة خدمة العملاء (24 ساعة) مغلقة. أرسل قالبًا معتمدًا لإعادة فتح المحادثة.', 'The 24-hour window is closed. Send an approved template to re-open the conversation.')}</div> : st === 'closing_soon' ? <div className="notifier" style={{ margin: 0, borderRadius: 0 }}><Clock size={14} style={{ display: 'inline', marginInlineEnd: 6 }} />{t('نافذة 24 ساعة على وشك الإغلاق — أنهِ ردك أو أرسل قالبًا.', 'Window closing soon.')}</div> : null}
          {editable && <div className="chat-compose"><Textarea aria-label="نص رسالة واتساب" placeholder={closed ? 'أعد فتح المحادثة أولًا' : st === 'closed' ? 'النافذة مغلقة — استخدم قالبًا معتمدًا' : t('اكتب رد… (Enter للإرسال، Shift+Enter سطر جديد)', 'Write a reply…')} value={text} disabled={freeformDisabled} rows={2} onChange={e => setText(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send(); } }} /><div className="stack" style={{ gap: 6 }}><Button disabled={freeformDisabled || !text.trim() || busy} onClick={send}><Send size={16} /></Button><Button variant="outline" disabled={closed || !acc?.isActive || busy} onClick={() => setPicker(true)} title={t('قالب معتمد', 'Template')}><LayoutTemplate size={16} /></Button></div></div>}
          {!editable && !closed && <div className="insight" style={{ borderRadius: 0 }}><Info size={16} />{j && !j.ownerId ? t('الرحلة بلا مالكة بعد — أسندها أو انتظر قبول عرض التوزيع قبل الرد.', 'Unassigned journey: assign it before replying.') : !j ? t('غير مرتبطة برحلة — تُربط من طابور المراجعة.', 'Not linked to a journey.') : t('العرض فقط: المحادثة تتبع مالكة الرحلة الحالية.', 'Read only: the conversation follows the current owner.')}</div>}
          <div className="demo-banner"><span>{t('الإرسال داخل التجربة فقط · providerMessageId محاكى', 'Demo only')}</span>{j && <button className="link-button" onClick={() => open('receive_reply', { id: j.id })}>{t('محاكاة رد العميل', 'Simulate a reply')}</button>}</div>
        </div> : <Empty />}
        {c && <aside style={{ padding: 16, display: 'grid', gap: 14, alignContent: 'start', borderInlineStart: '1px solid var(--border)' }}>
          {review(c) && <div className="notifier" style={{ margin: 0 }}><ShieldAlert size={14} style={{ display: 'inline', marginInlineEnd: 6 }} />{t('هذه المحادثة في طابور المراجعة.', 'Needs review.')} {a.role !== 'agent' && <button className="link-button" onClick={() => go('wa-reviews')}>{t('افتح المراجعات', 'Open reviews')}</button>}</div>}
          <div><p className="eyebrow">{t('جهة الاتصال', 'Contact')}</p><dl className="info-list"><div className="info-row"><dt>الاسم</dt><dd>{nameOf(c)}</dd></div><div className="info-row"><dt>الهاتف</dt><dd className="mono">{c.phone}</dd></div>{c.personId && <div className="info-row"><dt>الملف</dt><dd className="mono">{c.personId}</dd></div>}</dl></div>
          <div><p className="eyebrow">{t('الرحلة المرتبطة', 'Linked lead')}</p>{j ? <dl className="info-list"><div className="info-row"><dt>الشركة</dt><dd>{product(s, j.productId).company} · {product(s, j.productId).name}</dd></div><div className="info-row"><dt>المرحلة</dt><dd><StageMini stage={j.stage} /></dd></div><div className="info-row"><dt>الحالة</dt><dd>{j.status}</dd></div><div className="info-row"><dt>SLA</dt><dd><SLA j={j} /></dd></div><div className="info-row"><dt>المالكة</dt><dd>{s.agents.find(u => u.id === j.ownerId)?.name || '—'}</dd></div></dl> : <p className="small muted">{t('غير مرتبطة برحلة. الربط يتم من المراجعة أو عند إنشاء ليد.', 'Not linked.')}</p>}{j && <Button variant="outline" size="sm" className="mt" onClick={() => go(`leads/${j.id}`)}><ExternalLink size={14} />{t('فتح الملف', 'Open lead')}</Button>}</div>
          <div><p className="eyebrow">{t('الملكية', 'Ownership')}</p><dl className="info-list"><div className="info-row"><dt>المالكة</dt><dd>{c.assignedToId ? s.agents.find(u => u.id === c.assignedToId)?.name : '—'}</dd></div><div className="info-row"><dt>المصدر</dt><dd>{c.assignmentSource ? SOURCE_LABEL[c.assignmentSource] : '—'}</dd></div><div className="info-row"><dt>الحالة</dt><dd>{c.status === 'open' ? 'مفتوحة' : 'مغلقة'}</dd></div><div className="info-row"><dt>أُسندت</dt><dd>{c.assignedAt ? <DateText at={c.assignedAt} time /> : '—'}</dd></div>{c.handoverMode && <div className="info-row"><dt>وضع التسليم</dt><dd>{c.handoverMode}</dd></div>}</dl></div>
          <p className="small muted">{t('خارج نافذة 24 ساعة: قوالب معتمدة فقط. الاحتفاظ بالمحتوى 24 شهرًا.', 'Outside 24h: approved templates only.')}</p>
        </aside>}
      </div>
    </Panel>
    {picker && j && acc && <TemplatePicker journey={j} accountId={acc.id} close={() => setPicker(false)} />}
    {dialog && c && <AssignDialog conv={c} mode={dialog} close={() => setDialog(null)} />}
  </>;
}

/* ---------- template picker (new — production stubs this with a toast) ---------- */
export function TemplatePicker({ journey, accountId, close }: { journey: Journey; accountId: string; close: () => void }) {
  const { s, a, t, action, busy } = useMasar();
  const list = s.waTemplates.filter(x => x.accountId === accountId && x.status === 'approved');
  const [id, setId] = useState(list[0]?.id || ''), [vars, setVars] = useState<string[]>([]), [error, setError] = useState('');
  const tpl = list.find(x => x.id === id);
  const pe = person(s, journey);
  useEffect(() => { if (!tpl) return; const defaults = Array.from({ length: tpl.variableCount }, (_, i) => i === 0 ? pe.name.split(' ')[0] : i === 1 && tpl.name.startsWith('welcome') ? a.name.split(' ')[0] : ''); setVars(defaults); }, [id]);
  const preview = tpl ? renderTemplateBody(tpl.bodyText, vars) : '';
  return <Dialog open onOpenChange={v => !v && close()}><DialogContent className="form-dialog" dir="rtl"><DialogHeader><DialogTitle style={{ textAlign: 'start' }}>{t('إرسال قالب معتمد', 'Send approved template')}</DialogTitle><DialogDescription style={{ textAlign: 'start' }}>{t('القوالب المعتمدة فقط، ومتاحة داخل النافذة وخارجها. المتغيرات بالترتيب {{1}}، {{2}}…', 'Approved templates only.')}</DialogDescription></DialogHeader>
    {list.length ? <div className="stack">
      <div className="fields"><div className="field wide"><label>{t('القالب', 'Template')}</label><Pick value={id} onChange={setId} options={list.map(x => ({ value: x.id, label: `${x.name} · ${x.language} · ${x.category}` }))} /></div>
        {tpl && Array.from({ length: tpl.variableCount }, (_, i) => <div className="field" key={i}><label>{`{{${i + 1}}}`}</label><Input value={vars[i] ?? ''} onChange={e => setVars(v => { const n = [...v]; n[i] = e.target.value; return n; })} /></div>)}</div>
      {tpl && <div className="chat-messages" style={{ minHeight: 0, maxHeight: 'none', padding: 16 }}><div className="bubble out"><span className="pill blue" style={{ marginBottom: 6, display: 'inline-flex' }}><LayoutTemplate size={11} />{tpl.name}</span>{preview}</div></div>}
      {error && <p role="alert" className="form-error">{error}</p>}
      <div className="form-footer"><Button variant="outline" onClick={close}>إلغاء</Button><Button disabled={!tpl || busy || vars.some(v => !v.trim())} onClick={async () => { try { await action({ type: 'wa_send_template', id: journey.id, templateId: id, variables: vars }); close(); } catch (e) { setError(e instanceof Error ? e.message : 'تعذّر الإرسال'); } }}><Send size={15} />{t('إرسال القالب', 'Send')}</Button></div>
    </div> : <Empty text={t('لا قوالب معتمدة لهذا الحساب. سجّل قالبًا من صفحة القوالب.', 'No approved templates for this account.')} />}
  </DialogContent></Dialog>;
}

function AssignDialog({ conv, mode, close }: { conv: Conversation; mode: 'assign' | 'handover'; close: () => void }) {
  const { s, t, action, busy } = useMasar();
  const acc = s.waAccounts.find(x => x.id === conv.accountId)!;
  const agents = s.agents.filter(u => u.role === 'agent' && u.enabled && u.productId === acc.productId && u.id !== conv.assignedToId);
  const [agentId, setAgentId] = useState(agents[0]?.id || ''), [hm, setHm] = useState<'full' | 'summary' | 'clean'>('full'), [summary, setSummary] = useState(''), [error, setError] = useState('');
  return <Dialog open onOpenChange={v => !v && close()}><DialogContent className="form-dialog" dir="rtl"><DialogHeader><DialogTitle style={{ textAlign: 'start' }}>{mode === 'assign' ? t('إسناد المحادثة', 'Assign conversation') : t('تسليم المحادثة والرحلة', 'Handover')}</DialogTitle><DialogDescription style={{ textAlign: 'start' }}>{mode === 'assign' ? 'assignmentSource: manual_handover · الملكية لا تُسرق من مالكة نشطة إلا يدويًا.' : 'full: كل التاريخ · summary: يُخفى السابق مع ملخص · clean: يُخفى السابق وتُغلق المحادثة.'}</DialogDescription></DialogHeader>
    <div className="fields"><div className="field wide"><label>الموظفة</label><Pick value={agentId} onChange={setAgentId} options={agents.map(u => ({ value: u.id, label: `${u.name} · ${u.team}` }))} /></div>{mode === 'handover' && <><div className="field"><label>وضع التسليم</label><Pick value={hm} onChange={v => setHm(v as typeof hm)} options={[{ value: 'full', label: 'full · كامل' }, { value: 'summary', label: 'summary · ملخص' }, { value: 'clean', label: 'clean · نظيف' }]} /></div>{hm === 'summary' && <div className="field wide"><label>ملخص التسليم *</label><Textarea rows={3} value={summary} onChange={e => setSummary(e.target.value)} /></div>}</>}</div>
    {error && <p role="alert" className="form-error">{error}</p>}
    <div className="form-footer"><Button variant="outline" onClick={close}>إلغاء</Button><Button disabled={!agentId || busy} onClick={async () => { try { await action({ type: 'wa_conversation', id: conv.id, op: mode, agentId, mode: hm, summary }); close(); } catch (e) { setError(e instanceof Error ? e.message : 'تعذّر'); } }}>{t('تنفيذ', 'Apply')}</Button></div>
  </DialogContent></Dialog>;
}

/* ---------- templates admin (mirrors apps/web/app/admin/whatsapp/templates) ---------- */
export function TemplatesPage() {
  const { s, a, t, action, busy } = useMasar();
  const [create, setCreate] = useState(false), [status, setStatus] = useState('all'), [account, setAccount] = useState('all');
  const list = s.waTemplates.filter(x => (status === 'all' || x.status === status) && (account === 'all' || x.accountId === account)).sort((x, y) => x.status.localeCompare(y.status) || x.name.localeCompare(y.name) || x.language.localeCompare(y.language));
  const tone = (st: string) => st === 'approved' ? 'green' : st === 'rejected' ? 'red' : 'gold';
  return <>
    <Head title={t('قوالب واتساب', 'WhatsApp templates')} subtitle={t('الاعتماد يتم في Meta WABA؛ هنا نسجّل القالب المعتمد ونتحكم في إتاحته للفريق', 'Approval happens in the WABA console; the CRM records approved templates')} actions={<><Pick value={status} onChange={setStatus} options={[{ value: 'all', label: 'كل الحالات' }, ...TEMPLATE_STATUSES.map(x => ({ value: x, label: x }))]} />{s.waAccounts.length > 1 && <Pick value={account} onChange={setAccount} options={[{ value: 'all', label: 'كل الحسابات' }, ...s.waAccounts.map(x => ({ value: x.id, label: x.displayName }))]} />}{a.role !== 'agent' && <Button onClick={() => setCreate(true)} disabled={!s.waAccounts.length}><Plus size={16} />{t('تسجيل قالب', 'Record template')}</Button>}</>} />
    <div className="stats-grid" style={{ marginBottom: 16 }}>{TEMPLATE_STATUSES.map(st => <div key={st} className="panel stat" style={{ '--stage': st === 'approved' ? 'var(--good)' : st === 'rejected' ? 'var(--critical)' : 'var(--warn)' } as React.CSSProperties}><div className="stat-icon"><LayoutTemplate size={20} /></div><div><strong>{s.waTemplates.filter(x => x.status === st).length}</strong><p>{st}</p></div></div>)}<div className="panel stat" style={{ '--stage': 'var(--brand-500)' } as React.CSSProperties}><div className="stat-icon"><MessageSquare size={20} /></div><div><strong>{s.messages.filter(m => m.messageType === 'template').length}</strong><p>{t('رسائل قوالب مُرسلة', 'Template sends')}</p></div></div></div>
    <Panel body={false}>{list.length ? <div className="scroll-x"><Table className="data-table"><TableHeader><TableRow>{['القالب', 'الحساب', 'الفئة', 'المتغيرات', 'الحالة', 'النص', ''].map(x => <TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{list.map(x => <TableRow key={x.id}><TableCell><strong>{x.name}</strong><div className="mono small muted">{x.language}</div></TableCell><TableCell>{s.waAccounts.find(y => y.id === x.accountId)?.displayName || x.accountId.slice(0, 8)}</TableCell><TableCell style={{ textTransform: 'uppercase', fontSize: 12 }}>{x.category}</TableCell><TableCell className="mono">{x.variableCount}</TableCell><TableCell><Pill color={tone(x.status)}>{x.status}</Pill></TableCell><TableCell style={{ maxWidth: 380, whiteSpace: 'normal' }}><span className="small">{x.bodyText}</span></TableCell><TableCell>{a.role !== 'agent' && <div className="actions" style={{ flexWrap: 'nowrap' }}>{x.status !== 'rejected' && <Button size="sm" variant="outline" disabled={busy} onClick={() => action({ type: 'wa_template_save', id: x.id, accountId: x.accountId, category: x.category, bodyText: x.bodyText, status: x.status === 'approved' ? 'paused' : 'approved' }).catch(() => { })}>{x.status === 'approved' ? <><Pause size={13} />إيقاف</> : <><Play size={13} />تفعيل</>}</Button>}<Button size="sm" variant="ghost" aria-label="حذف" disabled={busy} onClick={() => { if (window.confirm(`حذف القالب ${x.name}؟`)) action({ type: 'wa_template_delete', id: x.id }).catch(() => { }); }}><Trash2 size={14} /></Button></div>}</TableCell></TableRow>)}</TableBody></Table></div> : <Empty text={t('لا قوالب في هذا العرض', 'No templates')} />}</Panel>
    <div className="insight mt"><Info size={17} /><p>{t('variableCount = أعلى رقم متغير في النص (وليس عدد المتغيرات المميزة). الاسم واللغة والحساب لا تتغير بعد التسجيل؛ paused تمنع الإرسال فورًا، وrejected تسجّل قرار Meta.', 'variableCount is the max placeholder index; name, language and account are immutable.')}</p></div>
    {create && <TemplateDialog close={() => setCreate(false)} />}
  </>;
}

function TemplateDialog({ close }: { close: () => void }) {
  const { s, t, action, busy } = useMasar();
  const [d, setD] = useState({ accountId: s.waAccounts[0]?.id || '', name: '', language: 'ar', category: 'utility', bodyText: '', status: 'approved' }), [error, setError] = useState('');
  const set = (k: string, v: string) => setD(x => ({ ...x, [k]: v }));
  return <Dialog open onOpenChange={v => !v && close()}><DialogContent className="form-dialog" dir="rtl"><DialogHeader><DialogTitle style={{ textAlign: 'start' }}>{t('تسجيل قالب معتمد', 'Record template')}</DialogTitle><DialogDescription style={{ textAlign: 'start' }}>{t('نفس حقول الإنتاج: الحساب، الاسم snake_case، اللغة BCP-47، الفئة، النص بمتغيرات {{1}} {{2}}، الحالة.', 'Same fields as production.')}</DialogDescription></DialogHeader>
    <form onSubmit={async e => { e.preventDefault(); setError(''); try { await action({ type: 'wa_template_save', ...d }); close(); } catch (er) { setError(er instanceof Error ? er.message : 'تعذّر الحفظ'); } }}><div className="fields">
      <div className="field wide"><label>الحساب *</label><Pick value={d.accountId} onChange={v => set('accountId', v)} options={s.waAccounts.map(x => ({ value: x.id, label: `${x.displayName} (${x.phoneNumber})` }))} /></div>
      <div className="field"><label>الاسم *</label><Input value={d.name} onChange={e => set('name', e.target.value)} pattern="[a-z][a-z0-9_]*" maxLength={100} placeholder="appointment_reminder" required dir="ltr" /><small>snake_case بحروف صغيرة</small></div>
      <div className="field"><label>اللغة *</label><Input value={d.language} onChange={e => set('language', e.target.value)} maxLength={10} placeholder="ar · en · en_US" required dir="ltr" /><small>BCP-47</small></div>
      <div className="field"><label>الفئة *</label><Pick value={d.category} onChange={v => set('category', v)} options={TEMPLATE_CATEGORIES.map(x => ({ value: x, label: x }))} /></div>
      <div className="field"><label>الحالة</label><Pick value={d.status} onChange={v => set('status', v)} options={TEMPLATE_STATUSES.map(x => ({ value: x, label: x }))} /></div>
      <div className="field wide"><label>النص *</label><Textarea rows={4} maxLength={2048} value={d.bodyText} onChange={e => set('bodyText', e.target.value)} required /><small>استخدم {'{{1}}'}، {'{{2}}'} للمتغيرات بالترتيب · المتغيرات المكتشفة: {countTemplateVariables(d.bodyText)}</small></div>
    </div>{error && <p role="alert" className="form-error">{error}</p>}<div className="form-footer"><Button type="button" variant="outline" onClick={close}>إلغاء</Button><Button type="submit" disabled={busy}>{t('تسجيل القالب', 'Record')}</Button></div></form>
  </DialogContent></Dialog>;
}

/* ---------- review queue (mirrors apps/web/app/admin/whatsapp/reviews) ---------- */
export function ReviewsPage() {
  const { s, a, t, go, action, busy } = useMasar();
  const [tab, setTab] = useState<'active' | 'resolved'>('active'), [reason, setReason] = useState('all'), [resolve, setResolve] = useState<{ r: WhatsAppReview; res: ReviewResolution } | null>(null);
  const list = s.waReviews.filter(r => (tab === 'active' ? !r.resolvedAt : !!r.resolvedAt) && (reason === 'all' || r.reason === reason)).sort((x, y) => y.createdAt - x.createdAt);
  const canAct = a.role !== 'agent';
  return <>
    <Head title={t('مراجعات واتساب', 'WhatsApp reviews')} subtitle={t('رسائل واردة لم يمكن توجيهها تلقائيًا: كابتن نشط، رحلات متعددة، أو لا مرشحة', 'Inbound that could not be routed automatically')} actions={<><div className="segmented"><button className={tab === 'active' ? 'active' : ''} onClick={() => setTab('active')}>{t('نشطة', 'Active')} {s.waReviews.filter(r => !r.resolvedAt).length}</button><button className={tab === 'resolved' ? 'active' : ''} onClick={() => setTab('resolved')}>{t('محسومة', 'Resolved')}</button></div><Pick value={reason} onChange={setReason} options={[{ value: 'all', label: 'كل الأسباب' }, ...Object.keys(REASON_LABEL).map(k => ({ value: k, label: REASON_LABEL[k][0] }))]} /></>} />
    {list.length ? <div className="stack">{list.map(r => { const conv = s.conversations.find(c => c.id === r.conversationId)!, [label, why, tone] = REASON_LABEL[r.reason], nm = (r.personId && s.people.find(p => p.id === r.personId)?.name) || conv?.phone; const cands = r.candidateJourneyIds.map(id => s.journeys.find(j => j.id === id)).filter(Boolean) as Journey[]; return <Panel key={r.id}><div className="row-between" style={{ alignItems: 'flex-start' }}><div><div className="actions"><Pill color={tone}>{label}</Pill>{r.resolvedAt && <Pill color="green">محسومة · {r.resolution}</Pill>}<DateText at={r.createdAt} time /></div><p className="small muted mt" style={{ marginTop: 6 }}>{why}</p></div><button className="view-link" onClick={() => go(`inbox?journey=${conv?.journeyId || ''}`)}>{t('افتح المحادثة', 'Open thread')} ↗</button></div>
      <div className="person-cell mt"><Avatar name={nm || '?'} /><div><strong>{nm}</strong><small>{conv?.phone}</small></div></div>
      {r.contextSnapshot.length > 0 && <div className="call-evidence mt"><p className="eyebrow">{t('آخر الرسائل', 'Recent messages')}</p>{r.contextSnapshot.map((m, i) => <p key={i} className="small">«{m.text}» <DateText at={m.createdAt} time /></p>)}</div>}
      {r.reason === 'captain_active' && r.candidateCaptainJourneyId && <p className="small mt">{t('الكابتن المرشح:', 'Candidate captain:')} <button className="view-link" onClick={() => go(`leads/${r.candidateCaptainJourneyId}`)}>{r.candidateCaptainJourneyId}</button></p>}
      {cands.length > 0 && <div className="mt">{cands.slice(0, 3).map(j => <div className="followup" key={j.id}><StageMini stage={j.stage} /><span className="small">{product(s, j.productId).company} · {j.status} · {s.agents.find(u => u.id === j.ownerId)?.name || 'غير مسندة'}</span><span className="when">{canAct && !r.resolvedAt && <Button size="sm" variant="outline" disabled={busy} onClick={() => action({ type: 'wa_review_resolve', id: r.id, resolution: 'linked_to_lead', journeyId: j.id }).catch(() => { })}>{t('اربط بهذه الرحلة', 'Link to lead')}</Button>}</span></div>)}</div>}
      {!r.resolvedAt && (canAct ? <div className="actions mt">{r.reason === 'captain_active' && <Button variant="outline" onClick={() => setResolve({ r, res: 'linked_to_captain' })}>{t('اربط بالكابتن', 'Link to captain')}</Button>}{r.reason !== 'captain_active' && <Button onClick={() => setResolve({ r, res: 'new_lead' })}>{t('إنشاء ليد جديد', 'Create new lead')}</Button>}{r.reason === 'captain_active' && <Button variant="outline" onClick={() => setResolve({ r, res: 'new_attempt' })}>{t('دورة متابعة جديدة', 'New attempt')}</Button>}<Button variant="ghost" onClick={() => setResolve({ r, res: 'dismissed' })}>{t('تجاهل', 'Dismiss')}</Button></div> : <p className="small muted mt" style={{ fontStyle: 'italic' }}>{t('القرار لقائدة الفريق أو الإدارة.', 'Read only.')}</p>)}
    </Panel>; })}</div> : <Empty text={t('لا مراجعات في هذا العرض', 'No reviews')} />}
    {resolve && <Dialog open onOpenChange={v => !v && setResolve(null)}><DialogContent className="form-dialog" dir="rtl"><DialogHeader><DialogTitle style={{ textAlign: 'start' }}>{t('حسم المراجعة', 'Resolve review')}</DialogTitle><DialogDescription style={{ textAlign: 'start' }}>{resolve.res} · {REASON_LABEL[resolve.r.reason][0]}</DialogDescription></DialogHeader><p className="small">{({ linked_to_captain: 'لا يغيّر الحالة؛ يُسجّل أن الرقم يخص كابتن نشط وتبقى المحادثة مع مالكة رحلته.', new_lead: 'يُسند الليد/المحادثة لمن يحسم المراجعة (وليس لمحرك التوزيع) بمصدر inbound_route.', new_attempt: 'يبدأ دورة متابعة جديدة مرتبطة بالمحادثة، مسندة لمن يحسم المراجعة.', dismissed: 'لا يغيّر شيئًا؛ يُغلق عنصر المراجعة فقط.', linked_to_lead: '' })[resolve.res]}</p><div className="form-footer"><Button variant="outline" onClick={() => setResolve(null)}>إلغاء</Button><Button disabled={busy} onClick={() => action({ type: 'wa_review_resolve', id: resolve.r.id, resolution: resolve.res }).then(() => setResolve(null)).catch(() => { })}>{t('تأكيد', 'Confirm')}</Button></div></DialogContent></Dialog>}
  </>;
}

/* ---------- accounts panel (integrations) ---------- */
export function WhatsAppAccountsPanel() {
  const { s, a, t, action, busy } = useMasar();
  return <Panel title={t('حسابات واتساب (Meta Cloud API)', 'WhatsApp accounts')} body={false} action={<Pill color="green">{s.waAccounts.filter(x => x.isActive).length} {t('نشط', 'active')}</Pill>}><div className="scroll-x"><Table className="data-table"><TableHeader><TableRow>{['الحساب', 'الرقم', 'phone_number_id', 'المزود', 'App Secret', 'الحالة', 'آخر اختبار', ''].map(x => <TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{s.waAccounts.map(x => <TableRow key={x.id}><TableCell><strong>{x.displayName}</strong></TableCell><TableCell className="mono">{x.phoneNumber}</TableCell><TableCell className="mono">{x.phoneNumberId}</TableCell><TableCell>{x.provider}</TableCell><TableCell>{x.hasAppSecret ? <Pill color="green">مضبوط</Pill> : <Pill color="red">مفقود</Pill>}</TableCell><TableCell><Pill color={x.isActive ? 'green' : 'red'}>{x.isActive ? 'active' : 'disabled'}</Pill></TableCell><TableCell>{x.lastTest ? <span className="small"><Pill color={x.lastTest.ok ? 'green' : 'red'}>{x.lastTest.message}</Pill> <DateText at={x.lastTest.at} time /></span> : <span className="muted small">—</span>}</TableCell><TableCell>{canManage(a, x.productId) && <div className="actions" style={{ flexWrap: 'nowrap' }}><Button size="sm" variant="outline" disabled={busy} onClick={() => action({ type: 'wa_account', id: x.id, op: 'test' }).catch(() => { })}><RefreshCw size={13} />اختبار</Button><Button size="sm" variant="ghost" disabled={busy} onClick={() => action({ type: 'wa_account', id: x.id, op: x.isActive ? 'disable' : 'enable' }).catch(() => { })}>{x.isActive ? 'إيقاف' : 'تفعيل'}</Button></div>}</TableCell></TableRow>)}</TableBody></Table></div><div className="table-footer"><span>{t('الرمز السري لا يُعرض أبدًا · نتيجة الاختبار لا تُخزَّن في الإنتاج · الحساب الموقوف لا يرسل', 'Secrets never returned')}</span></div></Panel>;
}

/* ---------- lead detail card ---------- */
export function LeadWhatsAppCard({ j }: { j: Journey }) {
  const { s, t, go } = useMasar();
  const c = conversationFor(s, j);
  const msgs = c ? s.messages.filter(m => m.conversationId === c.id) : [];
  const last = msgs.sort((x, y) => y.at - x.at)[0];
  return <Panel title="WhatsApp" action={c ? <WindowPip conv={c} /> : undefined}>{c ? <dl className="info-list"><div className="info-row"><dt>الحالة</dt><dd>{c.status === 'open' ? 'مفتوحة' : 'مغلقة'} · {msgs.length} رسالة</dd></div><div className="info-row"><dt>المالكة</dt><dd>{s.agents.find(u => u.id === c.assignedToId)?.name || '—'} {c.assignmentSource && <span className="muted">({SOURCE_LABEL[c.assignmentSource]})</span>}</dd></div><div className="info-row"><dt>آخر رسالة</dt><dd>{last ? <>{last.direction === 'in' ? 'واردة' : STATUS_LABEL[last.state]} · <DateText at={last.at} time /></> : '—'}</dd></div><div className="info-row"><dt>آخر رد من العميل</dt><dd>{c.lastInboundAt ? <DateText at={c.lastInboundAt} time /> : '—'}</dd></div></dl> : <p className="small muted">{t('لا توجد محادثة بعد. أول قالب معتمد يفتح المحادثة.', 'No conversation yet.')}</p>}<Button variant="outline" size="sm" className="mt" onClick={() => go(`inbox?journey=${j.id}`)}><MessageSquare size={14} />{t('فتح في صندوق الوارد', 'Open in inbox')}</Button></Panel>;
}
