import assert from 'node:assert/strict';
import {seed,type State,type Command,uid,stages,M,H,D} from '../lib/masar/model';
import {execute,actor,scoped,route,bonus,firstDue,clockParts,canEdit} from '../lib/masar/engine';
import {serve,type Storage} from '../lib/masar/service';
let passed=0;function check(name:string,fn:()=>void){fn();passed++;console.log('PASS',name)}
const run=(s:State,c:Command,a='admin')=>execute(s,a,c,uid('TEST'));
check('One person / independent company journeys / server scope',()=>{const s=seed();assert.equal(s.journeys.filter(j=>j.personId==='P-24817').length,2);const v=scoped(s,actor(s,'a1'));assert(v.journeys.every(j=>j.productId==='uber-eg'));assert(!v.journeys.some(j=>j.id==='J-2001'));assert(!v.messages.some(m=>m.journeyId==='J-1002'));assert.throws(()=>run(s,{type:'note',id:'J-2001',text:'hidden'},'a1'))});
check('Notes / status changes do not count as a first attempt',()=>{let s=seed();s=run(s,{type:'note',id:'J-1001',text:'ملاحظة'},'a1');s=run(s,{type:'status',id:'J-1001',status:'تم التواصل'},'a1');assert.equal(s.journeys[0].firstAttemptAt,null);s=run(s,{type:'attempt',id:'J-1001',outcome:'لم يرد',duration:25},'a1');assert.equal(s.journeys[0].firstAttemptAt,s.now);assert.equal(s.journeys[0].successfulAt,null);assert.throws(()=>run(s,{type:'attempt',id:'J-1001',outcome:'لم يرد',duration:0},'a1'))});
check('Offline preserves SLA deadline and history',()=>{let s=seed(),due=s.journeys[0].dueAt;s=run(s,{type:'availability',id:'a1',value:'offline'},'a1');assert.equal(s.journeys[0].dueAt,due);assert.equal(route(s,s.journeys[0]).candidates.find(x=>x.agent.id==='a1')?.eligible,false)});
check('Idempotent intake / preserve external submissions',()=>{let s=seed();const cmd={type:'create_lead',name:'عميل تجريبي',phone:'+201055556666',productId:'uber-eg',source:'Meta',externalId:'UNIQUE-1'};s=run(s,cmd);const count=s.people.length,rev=s.revision;s=run(s,cmd);assert.equal(s.people.length,count);assert.equal(s.submissions.filter(x=>x.externalId==='UNIQUE-1').length,1);s=run(s,{...cmd,externalId:'UNIQUE-2'});assert.equal(s.people.length,count);assert.equal(s.submissions.filter(x=>x.externalId.startsWith('UNIQUE')).length,2)});
check('Verified milestone credits old owner, assigns by acceptance, last preceding ad',()=>{let s=seed();s.submissions.push({id:'latest',personId:'P-24817',journeyId:'J-1001',externalId:'LATEST',source:'Meta',at:s.now-M,answers:[]},{id:'future',personId:'P-24817',journeyId:'J-1001',externalId:'FUTURE',source:'Meta',at:s.now+H,answers:[]});s=run(s,{type:'transition',id:'J-1001'},'a1');assert.equal(s.journeys[0].stage,'signup');const out=s.outcomes.find(o=>o.journeyId==='J-1001')!;assert.equal(out.agentId,'a1');assert.equal(out.submissionId,'latest');const offer=s.offers.find(o=>o.journeyId==='J-1001'&&o.state==='pending')!;assert(offer);assert.equal(s.journeys[0].ownerId,'a1');assert.throws(()=>run(s,{type:'offer_decide',id:offer.id,accept:true},'a2'));s=run(s,{type:'offer_decide',id:offer.id,accept:true},offer.agentId);assert.equal(s.journeys[0].ownerId,offer.agentId);assert.throws(()=>run(s,{type:'note',id:'J-1001',text:'late'},'a1'));assert(!scoped(s,actor(s,'a1')).messages.some(m=>m.journeyId==='J-1001'));assert(s.outcomes.find(o=>o.id===out.id)?.valid);s=run(s,{type:'note',id:'J-1001',text:'private note after same-time handoff'},offer.agentId);assert(!scoped(s,actor(s,'a1')).activities.some(e=>e.detail==='private note after same-time handoff'))});
check('Same-time ad arrivals use arrival order, never lexical ID order',()=>{let s=seed();s.submissions.push({id:'ZZZ',personId:'P-24817',journeyId:'J-1001',externalId:'earlier',source:'Meta',at:s.now,answers:[]},{id:'AAA',personId:'P-24817',journeyId:'J-1001',externalId:'last',source:'TikTok',at:s.now,answers:[]});s=run(s,{type:'transition',id:'J-1001'},'a1');assert.equal(s.outcomes.find(o=>o.journeyId==='J-1001')!.submissionId,'AAA')});
check('Unverified milestone requires TL decision; rejection leaves stage',()=>{let s=seed();s=run(s,{type:'transition',id:'J-1003',reason:'تحقق من الشركة'},'a1');const ap=s.approvals[0];assert.equal(s.journeys[2].stage,'fresh');assert.equal(ap.type,'stage');assert.throws(()=>run(s,{type:'approval_decide',id:ap.id,accept:true,reason:'ok'},'a1'));s=run(s,{type:'approval_decide',id:ap.id,accept:false,reason:'الإثبات ناقص'},'tl');assert.equal(s.journeys[2].stage,'fresh');assert.equal(s.approvals[0].state,'rejected')});
check('Rotation keeps previous denominator, adds new exposure on acceptance',()=>{let s=seed();s.sla[0].blockOverdue=false;s.rotation[0].afterMinutes=0;const p=s.bonusPlans[0],before=bonus(s,p,'a1','2026-09').denominator;s=run(s,{type:'rotate',id:'J-1001',ruleId:s.rotation[0].id},'tl');assert.equal(s.journeys[0].ownerId,'a1');const of=s.offers.find(o=>o.journeyId==='J-1001'&&o.state==='pending')!;s=run(s,{type:'offer_decide',id:of.id,accept:true},of.agentId);assert.equal(bonus(s,p,'a1','2026-09').denominator,before);assert(s.exposures.some(e=>e.journeyId==='J-1001'&&e.agentId===of.agentId&&e.kind==='rotation'));assert.equal(s.journeys[0].rotations,1)});
check('No eligible recipient does not steal ownership; capacity and cooldown guard',()=>{const s=seed();s.sla[0].blockOverdue=false;s.agents.find(a=>a.id==='a2')!.capacity=1;s.rotation[0].afterMinutes=0;assert.throws(()=>run(s,{type:'rotate',id:'J-1001',ruleId:s.rotation[0].id}));assert.equal(s.journeys[0].ownerId,'a1');s.journeys[0].rotations=3;assert.throws(()=>run(s,{type:'rotate',id:'J-1001',ruleId:s.rotation[0].id}))});
check('Highest tier applies to every result: 30 / 100 = 30%, 30 × 30 = 900',()=>{const s=seed();s.people=[];s.journeys=[];s.exposures=[];s.outcomes=[];for(let i=0;i<100;i++){const pe={id:`P-${i}`,name:`Person ${i}`,phones:[`+2010${String(i).padStart(8,'0')}`],city:'Cairo',createdAt:s.now-D};s.people.push(pe);s.journeys.push({...seed().journeys[0],id:`J-${i}`,personId:pe.id,createdAt:pe.createdAt});s.exposures.push({id:`E-${i}`,journeyId:`J-${i}`,personId:pe.id,agentId:'a1',stage:'fresh',at:s.now-D,kind:'fresh',excluded:false});if(i<30)s.outcomes.push({id:`O-${i}`,journeyId:`J-${i}`,personId:pe.id,agentId:'a1',from:'fresh',to:'signup',at:s.now,receivedAt:s.now-D,evidence:'verified',valid:true})}const b=bonus(s,s.bonusPlans[0],'a1','2026-09');assert.equal(b.denominator,100);assert.equal(b.numerator,30);assert.equal(b.rate,30);assert.equal(b.amount,900);s.now=Date.parse('2026-10-01T12:00:00Z');const next=run(s,{type:'bonus_snapshot',planId:s.bonusPlans[0].id,month:'2026-09'});const snap=next.snapshots.find(x=>x.agentId==='a1')!;assert.equal(snap.amount,900);const corrected=run(next,{type:'invalidate_outcome',id:'O-0',reason:'تصحيح'});assert.equal(corrected.snapshots.find(x=>x.id===snap.id)!.amount,900)});
check('Mixed and cohort modes deliberately differ for older data',()=>{const s=seed();const mixed=bonus(s,s.bonusPlans[0],'a1','2026-09'),cohort=bonus(s,{...s.bonusPlans[0],mode:'cohort'},'a1','2026-09');assert(mixed.numerator>cohort.numerator);assert(mixed.outcomes.some(o=>s.journeys.find(j=>j.id===o.journeyId)!.createdAt<Date.parse('2026-09-01')))});
check('Night SLA honors holidays and company timezone',()=>{const s=seed();s.now=Date.parse('2026-09-12T20:00:00Z');s.sla[0].holidays=['2026-09-13'];const due=firstDue(s,s.journeys[0]);const p=clockParts(due,'Africa/Cairo');assert.equal(p.date,'2026-09-14');assert.equal(p.hour,10);assert.equal(p.minute,30)});
check('Approved leave excludes intake without clearing existing ownership',()=>{let s=seed();s=run(s,{type:'leave',agentId:'a2',from:s.now-M,to:s.now+D,reason:'إجازة'},'a2');const ap=s.approvals[0];s=run(s,{type:'approval_decide',id:ap.id,accept:true,reason:'موافق'},'tl');assert(route(s,s.journeys[0]).candidates.find(x=>x.agent.id==='a2')!.reasons.includes('إجازة معتمدة'));assert(s.journeys.some(j=>j.ownerId==='a2'))});
check('Cumulative trips are not added twice; correction needs reason',()=>{let s=seed();s.partnerRows.push({id:'trips',productId:'uber-eg',phone:s.people[4].phones[0],name:s.people[4].name,signup:true,approved:true,trips:30,asOf:s.now,journeyId:'J-1005',batchId:'B1'});s=run(s,{type:'sync_trips',id:'J-1005'});s=run(s,{type:'sync_trips',id:'J-1005'});assert.equal(s.journeys[4].trips,30);assert.equal(s.outcomes.filter(o=>o.journeyId==='J-1005'&&o.from==='trips').length,1);s.partnerRows.find(r=>r.id==='trips')!.trips=4;assert.throws(()=>run(s,{type:'sync_trips',id:'J-1005'}));s=run(s,{type:'sync_trips',id:'J-1005',reason:'تصحيح الشريك'});assert.equal(s.journeys[4].trips,4);assert(!s.outcomes.some(o=>o.journeyId==='J-1005'&&o.from==='trips'&&o.valid))});
check('Merge keeps phone aliases and submissions, refuses duplicate active journeys',()=>{let s=seed();assert.throws(()=>run(s,{type:'merge',id:'P-24794',targetId:'P-24817',reason:'نفس الشخص'}));s=run(s,{type:'archive',id:'J-1024',reason:'رقم قديم مكرر'});const before=s.submissions.length;s=run(s,{type:'merge',id:'P-24794',targetId:'P-24817',reason:'تأكيد العميل'});assert.equal(s.people.find(p=>p.id==='P-24817')!.phones.length,2);assert.equal(s.submissions.length,before);assert(s.submissions.some(x=>x.journeyId==='J-1024'&&x.personId==='P-24817'))});
check('Team transfer keeps account and ledger; closes previous access',()=>{let s=seed();const ex=s.exposures.filter(e=>e.agentId==='a1').length;s=run(s,{type:'transfer_user',id:'a1',productId:'indrive-eg',team:'فريق جديد',stages:['fresh'],mode:'queue'});assert.equal(s.exposures.filter(e=>e.agentId==='a1').length,ex);assert(!s.journeys.some(j=>j.state==='open'&&j.ownerId==='a1'));assert(scoped(s,actor(s,'a1')).journeys.every(j=>j.productId==='indrive-eg'))});
check('Create product and employee without crossing scope',()=>{let s=seed();s=run(s,{type:'product_create',name:'Delivery',company:'Partner',country:'مصر',timezone:'Africa/Cairo',number:'+201077776666'});const p=s.products.at(-1)!;s=run(s,{type:'agent_create',name:'موظفة جديدة',productId:p.id,team:'فريق جديد',stages:['fresh']});assert.equal(s.agents.at(-1)!.productId,p.id);assert.throws(()=>run(s,{type:'product_create',name:'x'},'a1'))});
let saved=seed();const blobs=new Map<string,{bytes:Uint8Array;type:string}>();const store:Storage={async load(){return structuredClone(saved)},async save(_,s,rev){if(saved.revision!==rev)return false;saved=s;return true},async put(k,bytes,type){blobs.set(k,{bytes,type})},async get(k){return blobs.get(k)||null},async remove(k){blobs.delete(k)}};
const req=(c:Command,revision:number,id:string)=>new Request('http://localhost/api/action?actor=admin',{method:'POST',headers:{'Content-Type':'application/json','Origin':'http://localhost'},body:JSON.stringify({revision,requestId:id,command:c})});
let r=await serve(req({type:'note',id:'J-1001',text:'first'},0,'R1'),store,'test');assert.equal(r.status,200);r=await serve(req({type:'note',id:'J-1001',text:'stale'},0,'R2'),store,'test');assert.equal(r.status,409);r=await serve(req({type:'note',id:'J-1001',text:'first'},0,'R1'),store,'test');assert.equal(r.status,200);assert.equal(saved.revision,1);passed++;console.log('PASS API optimistic concurrency and request idempotency');
const form=new FormData();form.set('file',new File(['%PDF-1.4\nDemo'], 'proof.pdf',{type:'application/pdf'}));form.set('journeyId','J-1001');form.set('docType','بطاقة الهوية');form.set('revision',String(saved.revision));r=await serve(new Request('http://localhost/api/upload?actor=a1',{method:'POST',body:form}),store,'test');assert.equal(r.status,200);const doc=saved.documents[0];assert(doc);assert.equal(blobs.size,1);r=await serve(new Request(`http://localhost/api/file?actor=i1&key=${encodeURIComponent(doc.key)}`),store,'test');assert.equal(r.status,404);r=await serve(new Request(`http://localhost/api/file?actor=a1&key=${encodeURIComponent(doc.key)}`),store,'test');assert.equal(r.status,200);passed++;console.log('PASS Durable document flow and cross-company download isolation');


/* ---------- WhatsApp module (ported from production apps/api/src/whatsapp) ---------- */
check('24h window: freeform blocked before reply / after expiry; templates always allowed',()=>{let s=seed();const j='J-1005';assert.throws(()=>run(s,{type:'send_message',id:j,text:'hi'},'a5'),/قالب/);const tpl=s.waTemplates.find(t=>t.name==='welcome_uber_v3'&&t.accountId==='WA-uber-eg')!;assert.equal(tpl.variableCount,2);assert.throws(()=>run(s,{type:'wa_send_template',id:j,templateId:tpl.id,variables:['x']},'a5'),/متغير/);s=run(s,{type:'wa_send_template',id:j,templateId:tpl.id,variables:['خالد','إسراء']},'a5');const m=s.messages.filter(m=>m.journeyId===j).pop()!;assert.equal(m.messageType,'template');assert.equal(m.state,'sent');assert(m.text.includes('خالد'));s=run(s,{type:'receive_reply',id:j,text:'تمام'},'a5');s=run(s,{type:'send_message',id:j,text:'داخل النافذة'},'a5');s=run(s,{type:'advance_time',minutes:25*60});assert.throws(()=>run(s,{type:'send_message',id:j,text:'بعد 25 ساعة'},'a5'),/24/);const paused=s.waTemplates.find(t=>t.status==='paused')!;assert.throws(()=>run(s,{type:'wa_send_template',id:j,templateId:paused.id,variables:['a','b']},'a5'),/template_not_found/)});
check('Template CRUD mirrors production validation (snake_case, BCP-47, duplicate, max-index variables)',()=>{let s=seed();assert.throws(()=>run(s,{type:'wa_template_save',accountId:'WA-uber-eg',name:'Bad Name',language:'ar',category:'utility',bodyText:'x'},'tl'),/snake_case/);assert.throws(()=>run(s,{type:'wa_template_save',accountId:'WA-uber-eg',name:'ok_name',language:'arabic',category:'utility',bodyText:'x'},'tl'),/BCP-47/);assert.throws(()=>run(s,{type:'wa_template_save',accountId:'WA-uber-eg',name:'welcome_uber_v3',language:'ar',category:'utility',bodyText:'x'},'tl'),/بالفعل/);s=run(s,{type:'wa_template_save',accountId:'WA-uber-eg',name:'gap_vars',language:'en_US',category:'marketing',bodyText:'Hi {{1}}, see {{3}}'},'tl');const t=s.waTemplates.find(t=>t.name==='gap_vars')!;assert.equal(t.variableCount,3);s=run(s,{type:'wa_template_save',id:t.id,accountId:'WA-uber-eg',category:'utility',bodyText:'Hi {{1}}',status:'paused'},'tl');assert.equal(s.waTemplates.find(t=>t.name==='gap_vars')!.variableCount,1);assert.throws(()=>run(s,{type:'wa_template_save',accountId:'WA-uber-eg',name:'agent_try',language:'ar',category:'utility',bodyText:'x'},'a1'))});
check('Inbound from an active captain queues captain_active; resolution rules enforced',()=>{let s=seed();const cap=s.people.find(p=>p.id==='P-24813')!;s=run(s,{type:'inbound',productId:'uber-eg',phone:cap.phones[0],name:cap.name,text:'عايز أسجل صاحبي'});const r=s.waReviews.find(r=>r.personId===cap.id)!;assert.equal(r.reason,'captain_active');assert(r.contextSnapshot.length>=1&&r.contextSnapshot.length<=2);assert.throws(()=>run(s,{type:'wa_review_resolve',id:r.id,resolution:'linked_to_captain'},'a5'));s=run(s,{type:'wa_review_resolve',id:r.id,resolution:'linked_to_captain'},'tl');assert.equal(s.waReviews.find(x=>x.id===r.id)!.resolution,'linked_to_captain');assert.throws(()=>run(s,{type:'wa_review_resolve',id:r.id,resolution:'dismissed'},'tl'),/already_resolved/);let s2=seed();s2=run(s2,{type:'inbound',productId:'uber-eg',phone:'+201099998888',name:'رقم جديد',text:'مرحبا'});const conv=s2.conversations.find(c=>c.phone==='+201099998888')!;assert(conv.lastInboundAt);assert.throws(()=>run(s2,{type:'wa_review_resolve',id:'nope',resolution:'linked_to_captain'},'tl'))});
check('Conversation follows the journey owner; summary handover hides prior messages from the new owner',()=>{let s=seed();const conv=s.conversations.find(c=>c.journeyId==='J-1001')!;assert.equal(conv.assignedToId,'a1');s=run(s,{type:'wa_conversation',id:conv.id,op:'handover',agentId:'a2',mode:'summary',summary:'العميل مهتم ومحتاج الأوراق'},'tl');const c2=s.conversations.find(c=>c.id===conv.id)!;assert.equal(c2.assignedToId,'a2');assert.equal(c2.assignmentSource,'manual_handover');assert.equal(s.journeys.find(j=>j.id==='J-1001')!.ownerId,'a2');const v=scoped(s,actor(s,'a2'));assert(!v.messages.some(m=>m.conversationId===conv.id&&m.at<c2.assignedAt!));assert(v.activities.some(e=>e.title==='ملخص تسليم واتساب'));s=run(s,{type:'wa_conversation',id:conv.id,op:'close'},'a2');assert.equal(s.conversations.find(c=>c.id===conv.id)!.status,'closed');s=run(s,{type:'receive_reply',id:'J-1001',text:'رجعت'},'a2');assert.equal(s.conversations.filter(c=>c.phone===conv.phone&&c.accountId===conv.accountId&&c.status==='open').length,1);assert.throws(()=>run(s,{type:'wa_conversation',id:conv.id,op:'reopen'},'a2'),/reopen_conflict/)});
check('Disabled account cannot send; enabling requires app secret; message status only moves forward',()=>{let s=seed();s=run(s,{type:'receive_reply',id:'J-1001',text:'اهلا'},'a1');s=run(s,{type:'wa_account',id:'WA-uber-eg',op:'disable'},'admin');assert.throws(()=>run(s,{type:'send_message',id:'J-1001',text:'x'},'a1'),/موقوف/);s=run(s,{type:'wa_account',id:'WA-uber-eg',op:'enable'},'admin');assert.throws(()=>run(s,{type:'wa_account',id:'WA-uber-sa',op:'enable'},'admin'),/app_secret/);s=run(s,{type:'send_message',id:'J-1001',text:'x'},'a1');const m=s.messages.filter(m=>m.journeyId==='J-1001'&&m.direction==='out').pop()!;s=run(s,{type:'wa_message_status',id:m.id,status:'read'},'admin');assert.throws(()=>run(s,{type:'wa_message_status',id:m.id,status:'delivered'},'admin'),/للخلف/);s=run(s,{type:'wa_account',id:'WA-uber-eg',op:'test'},'admin');assert.equal(s.waAccounts.find(a=>a.id==='WA-uber-eg')!.lastTest!.message,'Connection healthy')});
console.log(`\n${passed} acceptance scenarios passed.`);
